### ISSUE TITLE
lmdbjni-win64

### ISSUE THREAD

**Issue by henrib** [chirino/lmdbjni#5]
It would be nice to have a Windows 64 version of LMDB.
I haven't been able to get a working LMDB with cygwin64 (dumps core on mtest).
I've forked a "pure" windows version here (git@gitorious.org:mdb/henribs-mdb.git / https://gitorious.org/mdb/henribs-mdb/source/5f8c9800e88a3cc13117fd88da42ecedd8e2d4fd:) that can be compiled using MS Studio to produce a dll.
Would it be possible to add (back) an lmdbjni-win64 target that uses such a 'dll'  version?

**Comment by chirino** [comment]
sure send in a pull request /w some notes on how to build.

**Comment by henrib** [comment]
That's the issue... I'm seeking help to (re)activate the lmdbjni-win64 target; I was under the impression you tried to get it working and stopped because LMDB was not easily produced on Windows.
I'm trying to learn how to use hawtjni but the target aspects wrt configuration / platform are still eluding me (for now :-)).

Resurrecting the lmdbjni-win64 target so far just ends with errors in Maven, the native-package is not produced:
Source directory doesn't exists (C:\Users...\lmdbjni\lmdbjni-win64\target\generated-sources\hawtjni\native-package)

**Comment by castortech** [comment]
@henrib 

I have re-activated and rebuild the win64 version of lmdbjni and I intend to update my branch with it. If you need the jar, please let me know.

**Comment by henrib** [comment]
@castortech 
Good job; if you actually could commit it in your branch, that would be perfect.

**Comment by os72** [comment]
@castortech - do you happen to have a fully built jar containing all 3 native libs?

(Like the one here, but including win64)
http://repo.fusesource.com/nexus/content/repositories/snapshots/org/fusesource/lmdbjni/lmdbjni-all/99-master-SNAPSHOT/

**Comment by castortech** [comment]
I have win64 and linux built and working on getting the mac one done.

Alain

Alain Picard
Chief Strategy Officer
Benchmark Canada
514-798-2042

apicard@benchmarkcanada.com
www.benchmarkcanada.com

**Comment by henrib** [comment]
Hi Alain,
If you're still fighting with the Mac version (on OSX 10.9 / JDK7), the "configure" file generated by hawtjndi is "too old";  the logic for --with-jni-jdk (lines 10961-10986) that checks the presence of a usable JDK is wrong (looking for the header file in an Apple Java 6 JDK) and misses adding the "darwin" include (the JDK7 layout on Mac is the same as other Unixes).
On the windows 64 platform, I can't get the vs2010.vcproj to generate something that works without removing the <CharacterSet>Unicode</CharacterSet> (otherwise I get weird looking file names...) and I've had to massage some includes in the lmdb code. 
As a final note, I'm putting the lmdb code (i.e. the 4 important files lmdb.h mdb.c midl.h midl.c) in the same lmdbjni project (native-package/src) so I dont have to generate an external dl/.sol and it seems to work in early tests.
Fixing the whole seems to require modifying what hawjndi generates first; do you concur or did you find an alternative route ?
Cheers

**Comment by os72** [comment]
Guys, two comments:

Following project has a VS solution for LMDB (win32, x64 seems to work too). Perhaps useful?
https://github.com/ilyalukyanov/lightningdb-win

The JAR I had mentioned seems to include mac binaries. Again, perhaps useful?
http://repo.fusesource.com/nexus/content/repositories/snapshots/org/fusesource/lmdbjni/lmdbjni-all/99-master-SNAPSHOT/
